spring:
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:postgresql://localhost:5432/security-database
    username: postgres
    password: postgres12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect